-- create database customer_behavior;
USE customer_behavior;
SELECT 
    *
FROM
    customer;
	
    
    
    
-- 1) total revenue generated by male vs female customer
use customer_behavior;
SELECT 
    gender, SUM(purchase_amount) AS revenue
FROM
    customer
GROUP BY gender
ORDER BY revenue ASC;  


-- 2) which customer used a discount but still spent more than the avg purchase amount
use customer_behavior;
SELECT 
    *
FROM
    customer
WHERE
    purchase_amount > (SELECT 
            AVG(purchase_amount)
        FROM
            customer)
        AND discount_applied = 'yes';
        
        
        
-- 3) which are the top 5 products with the highest avg. review rating
use customer_behavior;
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS average_rating
FROM
    customer
GROUP BY item_purchased
ORDER BY average_rating DESC
LIMIT 5;        
        
        
        
 
 
 
 -- 4) compare avg. purchase amount between standard and express shipping
use customer_behavior;
SELECT 
    shipping_type, AVG(purchase_amount) AS average
FROM
    customer
WHERE
    shipping_type IN ('Express' , 'Standard')
GROUP BY shipping_type;





-- 5)  compare averge spend and total renevue beteween subscibe and non subscribes.Do subscibes customer spend more.
use customer_behavior;
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customer,
    SUM(purchase_amount) AS total_revenue,
    AVG(purchase_amount) AS average_spend
FROM
    customer
GROUP BY subscription_status;





-- 6) which 5 product have highest percentage of purchase with discount applied
use customer_behavior;
SELECT 
    item_purchased,
    ROUND(SUM(purchase_amount) * 100 / (SELECT 
                    SUM(purchase_amount)
                FROM
                    customer
                WHERE
                    discount_applied = 'Yes'),
            2) AS purchase_percentage
FROM
    customer
GROUP BY item_purchased
ORDER BY purchase_percentage DESC
LIMIT 5
; 





-- 7) top 3 most purchase products within each category
-- window function use row_number 
use customer_behavior;
with item_counts as(
select category,item_purchased,count(customer_id) as total_orders,
row_number()over(partition by category order by count(customer_id) desc) as item_rank from customer group by category,item_purchased
 )
 select item_rank,category,item_purchased,total_orders from item_counts where item_rank<=3; 
 
 
 
 
 
 -- 8) segment customer into new,returning and loyal based on their total no. of previous purchase and show count of each segment

with customer_type as(
select customer_id,previous_purchases,
case
when previous_purchases= 1 then 'new'
when previous_purchases between 1 and 10 then 'returning'
else 'loyal'
end as customer_segment from customer
)
select customer_segment,count(*) as number_of_segment from customer_type group by customer_segment;






-- 9) are customer who are repeat buyer (more than 5 prev purchases) also likely to subscribe
SELECT 
    subscription_status, COUNT(*)
FROM
    customer
WHERE
    previous_purchases > 5
GROUP BY subscription_status;





-- 10) revenue contribution of each age group
SELECT 
    age_group, SUM(purchase_amount) AS revenue
FROM
    customer
GROUP BY age_group;